Repository openshift/operator-framework-operator-controller, pull requests merged in 2024-07, with the labels that each got.

#115 NO-ISSUE: Synchronize From Upstream Repositories
  api/v1alpha1/clusterextension_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  commitchecker.yaml
  config/base/crd/bases/olm.operatorframework.io_clusterextensions.yaml
  config/samples/olm_v1alpha1_clusterextension.yaml
  go.mod
  go.sum
  internal/controllers/clusterextension_admission_test.go
  internal/controllers/clusterextension_controller_test.go
  internal/controllers/clusterextension_registryv1_validation_test.go
  openshift/generate-manifests.sh
  openshift/manifests/01-customresourcedefinition-clusterextensions.olm.operatorframework.io.yml
  test/e2e/cluster_extension_install_test.go
  test/extension-developer-e2e/extension_developer_test.go
  vendor/modules.txt
Labels: lgtm, jira/valid-reference, approved, tide/merge-method-merge

#117 NO-ISSUE: Synchronize From Upstream Repositories
  cmd/manager/main.go
  commitchecker.yaml
  go.mod
  go.sum
  internal/controllers/clusterextension_controller.go
  vendor/github.com/operator-framework/helm-operator-plugins/pkg/client/actionclient.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: lgtm, jira/valid-reference, approved, tide/merge-method-merge

#116 OPRUN-3436: UPSTREAM: <carry>: add openshift kustomize overlay
  openshift/generate-manifests.sh
  openshift/kustomize/overlays/openshift/kustomization.yaml
  openshift/kustomize/overlays/openshift/patches/manager_deployment_ca.yaml
  openshift/kustomize/overlays/openshift/resources/ca_configmap.yaml
  openshift/manifests/14-configmap-openshift-operator-controller-operator-controller-openshift-ca.yml
  openshift/manifests/15-service-openshift-operator-controller-operator-controller-controller-manager-metrics-service.yml
  openshift/manifests/16-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
Labels: lgtm, jira/valid-reference, approved

#120 [release-4.15] OCPBUGS-37549: Set required-scc for openshift workloads
  openshift/generate-manifests.sh
  openshift/manifests/11-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
Labels: lgtm, jira/valid-reference, cherry-pick-approved, approved, jira/valid-bug, backport-risk-assessed
