Repository openshift/operator-framework-operator-controller, pull requests merged in 2024-11, with the labels that each got.

#185 NO-ISSUE: Add HowTo for origin tests
  openshift/HOWTO-origin-tests.md
Labels: lgtm, jira/valid-reference, approved

#192 NO-ISSUE: Add e2e registry Dockerfile
  openshift/registry.Dockerfile
Labels: lgtm, jira/valid-reference, approved

#197 OCPBUGS-44813: UPSTREAM: <drop>: catalog cache: retry cache population when cache contains an error
  internal/catalogmetadata/cache/cache.go
  internal/catalogmetadata/cache/cache_test.go
  internal/controllers/clustercatalog_controller.go
  internal/controllers/clustercatalog_controller_test.go
  internal/controllers/clusterextension_controller.go
Labels: lgtm, qe-approved, jira/valid-reference, approved, jira/severity-critical, jira/valid-bug, acknowledge-critical-fixes-only

#198 OPRUN-3605: UPSTREAM: <carry>: namespace: use privileged PSA for audit and warn levels
  openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_namespace_privileged.yaml
  openshift/manifests/00-namespace-openshift-operator-controller.yml
Labels: lgtm, jira/valid-reference, approved, acknowledge-critical-fixes-only

#191 OPRUN-3587: Enable downstream e2e
  openshift/Makefile
  openshift/build-test-registry.sh
  openshift/registry.Dockerfile
Labels: lgtm, jira/valid-reference, approved
