Repository openshift/operator-framework-operator-controller, pull requests merged in 2025-05, with the labels that each got.

#325 OCPBUGS-56047: Bump catalog versions to 4.19 [main]
  openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-certified-operators.yaml
  openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-community-operators.yaml
  openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-redhat-marketplace.yaml
  openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-redhat-operators.yaml
  openshift/catalogd/manifests/19-clustercatalog-openshift-certified-operators.yml
  openshift/catalogd/manifests/20-clustercatalog-openshift-community-operators.yml
  openshift/catalogd/manifests/21-clustercatalog-openshift-redhat-marketplace.yml
  openshift/catalogd/manifests/22-clustercatalog-openshift-redhat-operators.yml
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug

#342 OCPBUGS-56047: revert "Bump catalog versions to 4.19 [main]"
  openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-certified-operators.yaml
  openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-community-operators.yaml
  openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-redhat-marketplace.yaml
  openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-redhat-operators.yaml
  openshift/catalogd/manifests/19-clustercatalog-openshift-certified-operators.yml
  openshift/catalogd/manifests/20-clustercatalog-openshift-community-operators.yml
  openshift/catalogd/manifests/21-clustercatalog-openshift-redhat-marketplace.yml
  openshift/catalogd/manifests/22-clustercatalog-openshift-redhat-operators.yml
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug

#338 NO-ISSUE: Update HOWTO-origin-tests
  openshift/HOWTO-origin-tests.md
Labels: lgtm, jira/valid-reference, approved

#345 NO-ISSUE: [DefaultCatalogTests]: Allow to pass auth path for docker credentials
  openshift/default-catalog-consistency/pkg/extract/extract.go
Labels: lgtm, jira/valid-reference, approved

#348 NO-ISSUE: <carry>: fix: set NoLchown=true to allow image unpack on OCPci
  openshift/default-catalog-consistency/pkg/extract/extract.go
Labels: lgtm, jira/valid-reference, approved

#347 NO-ISSUE: <carry>: [DefaultCatalogTests]: Moving parse of ENVVAR to the caller (follow-up 345)
  openshift/default-catalog-consistency/pkg/extract/extract.go
  openshift/default-catalog-consistency/test/validate/suite_test.go
Labels: lgtm, jira/valid-reference, approved

#351 NO-ISSUE: [Default Catalog]: Create tmp dir to extract layers with right permissions to avoid issues scenarios
  openshift/default-catalog-consistency/pkg/extract/extract.go
Labels: lgtm, jira/valid-reference, approved

#350 NO-ISSUE: [Default Catalog](cleanup) Remove hack directory which is not used
  openshift/default-catalog-consistency/hack/policy.json
Labels: lgtm, jira/valid-reference, approved

#358 NO-ISSUE: [Default Catalog Tests]: Final cleanups and enhancements of initial implementation
  openshift/default-catalog-consistency/Makefile
  openshift/default-catalog-consistency/README.md
  openshift/default-catalog-consistency/pkg/check/check.go
  openshift/default-catalog-consistency/pkg/check/image.go
  openshift/default-catalog-consistency/pkg/extract/extract.go
  openshift/default-catalog-consistency/test/utils/utils.go
  openshift/default-catalog-consistency/test/validate/suite_test.go
Labels: lgtm, jira/valid-reference, approved

#357 OCPBUGS-55918: set SELinux type for operator-controller
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
  openshift/operator-controller/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug, jira/severity-important

#343 OCPBUGS-56047: Bump catalog versions to 4.19 [main]
  openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-certified-operators.yaml
  openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-community-operators.yaml
  openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-redhat-marketplace.yaml
  openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-redhat-operators.yaml
  openshift/catalogd/manifests/19-clustercatalog-openshift-certified-operators.yml
  openshift/catalogd/manifests/20-clustercatalog-openshift-community-operators.yml
  openshift/catalogd/manifests/21-clustercatalog-openshift-redhat-marketplace.yml
  openshift/catalogd/manifests/22-clustercatalog-openshift-redhat-operators.yml
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug

#353 OCPBUGS-56045: [release-4.19] fix: don't template registry+v1 manifests
  internal/operator-controller/rukpak/convert/registryv1.go
  test/e2e/cluster_extension_install_test.go
  testdata/images/bundles/test-operator/v1.0.0/manifests/bundle.configmap.yaml
Labels: lgtm, jira/valid-reference, cherry-pick-approved, approved, jira/valid-bug, backport-risk-assessed
