Repository openshift/operator-framework-operator-controller, pull requests merged in 2025-02, with the labels that each got.

#267 NO-ISSUE: Remove vet from openshift verify
  openshift/Makefile
Labels: lgtm, jira/valid-reference, approved, acknowledge-critical-fixes-only

#269 NO-ISSUE: Skip another upstream test
  openshift/Makefile
Labels: lgtm, jira/valid-reference, approved, acknowledge-critical-fixes-only

#248 NO-ISSUE: Cleanup openshift/Makefile by removing no longer required comments regards catalogd e2e tests
  openshift/Makefile
Labels: lgtm, jira/valid-reference, approved, acknowledge-critical-fixes-only

#252 UPSTREAM: <carry>: OCPBUGS-49410: Enable OCP metrics collection by default
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/kustomization.yaml
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/metrics/catalogd_metrics_monitor_role.yaml
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/metrics/catalogd_metrics_monitor_role_binding.yaml
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/metrics/catalogd_metrics_monitor_servicemonitor.yaml
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/metrics/kustomization.yaml
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/patches/manager_namespace_monitored.yaml
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/patches/manager_namespace_privileged.yaml
  openshift/catalogd/manifests/00-namespace-openshift-catalogd.yml
  openshift/catalogd/manifests/04-role-openshift-catalogd-catalogd-metrics-monitor-role.yml
  openshift/catalogd/manifests/05-role-openshift-config-catalogd-manager-role.yml
  openshift/catalogd/manifests/06-clusterrole-catalogd-manager-role.yml
  openshift/catalogd/manifests/07-clusterrole-catalogd-metrics-reader.yml
  openshift/catalogd/manifests/08-clusterrole-catalogd-proxy-role.yml
  openshift/catalogd/manifests/09-rolebinding-openshift-catalogd-catalogd-leader-election-rolebinding.yml
  openshift/catalogd/manifests/10-rolebinding-openshift-catalogd-catalogd-metrics-monitor-rolebinding.yml
  openshift/catalogd/manifests/11-rolebinding-openshift-config-catalogd-manager-rolebinding.yml
  openshift/catalogd/manifests/12-clusterrolebinding-catalogd-manager-rolebinding.yml
  openshift/catalogd/manifests/13-clusterrolebinding-catalogd-proxy-rolebinding.yml
  openshift/catalogd/manifests/14-configmap-openshift-catalogd-catalogd-trusted-ca-bundle.yml
  openshift/catalogd/manifests/15-service-openshift-catalogd-catalogd-service.yml
  openshift/catalogd/manifests/16-deployment-openshift-catalogd-catalogd-controller-manager.yml
  openshift/catalogd/manifests/17-servicemonitor-openshift-catalogd-catalogd-metrics-monitor.yml
  openshift/catalogd/manifests/18-clustercatalog-openshift-certified-operators.yml
  openshift/catalogd/manifests/19-clustercatalog-openshift-community-operators.yml
  openshift/catalogd/manifests/20-clustercatalog-openshift-redhat-marketplace.yml
  openshift/catalogd/manifests/21-clustercatalog-openshift-redhat-operators.yml
  openshift/catalogd/manifests/22-mutatingwebhookconfiguration-catalogd-mutating-webhook-configuration.yml
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/kustomization.yaml
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/metrics/kustomization.yaml
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/metrics/operator_controller_metrics_monitor_role.yaml
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/metrics/operator_controller_metrics_monitor_rolebinding.yaml
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/metrics/operator_controller_metrics_monitor_servicemonitor.yaml
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_namespace_monitored.yaml
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_namespace_privileged.yaml
  openshift/operator-controller/manifests/00-namespace-openshift-operator-controller.yml
  openshift/operator-controller/manifests/06-role-openshift-operator-controller-operator-controller-metrics-monitor-role.yml
  openshift/operator-controller/manifests/07-clusterrole-operator-controller-clusterextension-editor-role.yml
  openshift/operator-controller/manifests/08-clusterrole-operator-controller-clusterextension-viewer-role.yml
  openshift/operator-controller/manifests/09-clusterrole-operator-controller-extension-editor-role.yml
  openshift/operator-controller/manifests/10-clusterrole-operator-controller-extension-viewer-role.yml
  openshift/operator-controller/manifests/11-clusterrole-operator-controller-manager-role.yml
  openshift/operator-controller/manifests/12-clusterrole-operator-controller-metrics-reader.yml
  openshift/operator-controller/manifests/13-clusterrole-operator-controller-proxy-role.yml
  openshift/operator-controller/manifests/14-rolebinding-openshift-config-operator-controller-manager-rolebinding.yml
  openshift/operator-controller/manifests/15-rolebinding-openshift-operator-controller-operator-controller-leader-election-rolebinding.yml
  openshift/operator-controller/manifests/16-rolebinding-openshift-operator-controller-operator-controller-manager-rolebinding.yml
  openshift/operator-controller/manifests/17-rolebinding-openshift-operator-controller-operator-controller-metrics-monitor-rolebinding.yml
  openshift/operator-controller/manifests/18-clusterrolebinding-operator-controller-manager-rolebinding.yml
  openshift/operator-controller/manifests/19-clusterrolebinding-operator-controller-proxy-rolebinding.yml
  openshift/operator-controller/manifests/20-configmap-openshift-operator-controller-operator-controller-trusted-ca-bundle.yml
  openshift/operator-controller/manifests/21-service-openshift-operator-controller-operator-controller-service.yml
  openshift/operator-controller/manifests/22-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
  openshift/operator-controller/manifests/23-servicemonitor-openshift-operator-controller-operator-controller-metrics-monitor.yml
Labels: lgtm, qe-approved, jira/valid-reference, approved, jira/valid-bug, jira/severity-important, acknowledge-critical-fixes-only

#274 [release-4.18] OCPBUGS-51141: Cache invalidate backport
  cmd/manager/main.go
  internal/rukpak/source/containers_image.go
  test/e2e/cluster_extension_install_test.go
  testdata/images/catalogs/test-catalog/v1/configs/catalog.yaml
Labels: lgtm, qe-approved, jira/valid-reference, cherry-pick-approved, approved, jira/valid-bug, backport-risk-assessed, jira/severity-important

#278 NO-ISSUE: Synchronize From Upstream Repositories
  .dockerignore
  .gitignore
  .goreleaser.yml
  Dockerfile.catalogd
  Dockerfile.operator-controller
  Makefile
  Tiltfile
  catalogd/Makefile
  catalogd/pprof/README.md
  catalogd/pprof/catalogd_apiserver_cpu_profile.pb
  catalogd/pprof/catalogd_apiserver_heap_profile.pb
  catalogd/pprof/images/controller_metrics.png
  catalogd/pprof/images/customapiserver_metrics.png
  catalogd/pprof/images/kubeapiserver_alone_metrics.png
  catalogd/pprof/images/kubeapiserver_metrics.png
  catalogd/pprof/kind.yaml
  catalogd/pprof/kubeapiserver_alone_cpu_profile.pb
  catalogd/pprof/kubeapiserver_alone_heap_profile.pb
  catalogd/pprof/kubeapiserver_cpu_profile.pb
  catalogd/pprof/kubeapiserver_heap_profile.pb
  catalogd/pprof/manager_cpu_profile.pb
  catalogd/pprof/manager_heap_profile.pb
  cmd/catalogd/main.go
  commitchecker.yaml
  config/base/operator-controller/rbac/extension_editor_role.yaml
  config/base/operator-controller/rbac/extension_viewer_role.yaml
  config/base/operator-controller/rbac/kustomization.yaml
  go.mod
  go.sum
  internal/catalogd/controllers/core/clustercatalog_controller_test.go
  openshift/catalogd.Dockerfile
  openshift/operator-controller/manifests/09-clusterrole-operator-controller-extension-editor-role.yml
  openshift/operator-controller/manifests/09-clusterrole-operator-controller-manager-role.yml
  openshift/operator-controller/manifests/10-clusterrole-operator-controller-extension-viewer-role.yml
  openshift/operator-controller/manifests/10-clusterrole-operator-controller-metrics-reader.yml
  openshift/operator-controller/manifests/11-clusterrole-operator-controller-proxy-role.yml
  openshift/operator-controller/manifests/12-rolebinding-openshift-config-operator-controller-manager-rolebinding.yml
  openshift/operator-controller/manifests/13-rolebinding-openshift-operator-controller-operator-controller-leader-election-rolebinding.yml
  openshift/operator-controller/manifests/14-rolebinding-openshift-operator-controller-operator-controller-manager-rolebinding.yml
  openshift/operator-controller/manifests/15-rolebinding-openshift-operator-controller-operator-controller-metrics-monitor-rolebinding.yml
  openshift/operator-controller/manifests/16-clusterrolebinding-operator-controller-manager-rolebinding.yml
  openshift/operator-controller/manifests/17-clusterrolebinding-operator-controller-proxy-rolebinding.yml
  openshift/operator-controller/manifests/18-configmap-openshift-operator-controller-operator-controller-trusted-ca-bundle.yml
  openshift/operator-controller/manifests/19-service-openshift-operator-controller-operator-controller-service.yml
  openshift/operator-controller/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
  openshift/operator-controller/manifests/21-servicemonitor-openshift-operator-controller-operator-controller-metrics-monitor.yml
  test/e2e/metrics_test.go
  vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/v4/README.md
  vendor/github.com/go-jose/go-jose/v4/jwe.go
  vendor/github.com/go-jose/go-jose/v4/jwk.go
  vendor/github.com/go-jose/go-jose/v4/jws.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/modules.txt
Labels: lgtm, jira/valid-reference, approved, tide/merge-method-merge

#280 OCPBUGS-52161: imageutil: unset PAXRecords and Xattrs in image layers when applying to disk
  internal/shared/util/image/filters.go
  internal/shared/util/image/filters_test.go
Labels: lgtm, qe-approved, jira/valid-reference, approved, jira/valid-bug, jira/severity-important
