Repository openshift/operator-framework-operator-controller, pull requests merged in 2025-01, with the labels that each got.

#226 OPRUN-3681: Add support for proxy trustedCAs
  openshift/kustomize/overlays/openshift/olmv1-ns/kustomization.yaml
  openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_ca.yaml
  openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
  openshift/kustomize/overlays/openshift/olmv1-ns/trusted-ca/operator_controller_trusted_ca_configmap.yaml
  openshift/manifests/18-configmap-openshift-operator-controller-operator-controller-trusted-ca-bundle.yml
  openshift/manifests/19-service-openshift-operator-controller-operator-controller-service.yml
  openshift/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
Labels: lgtm, qe-approved, jira/valid-reference, approved, acknowledge-critical-fixes-only

#230 OCPBUGS-48639: Add support for proxy trustedCAs
  openshift/kustomize/overlays/openshift/olmv1-ns/kustomization.yaml
  openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_ca.yaml
  openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
  openshift/kustomize/overlays/openshift/olmv1-ns/trusted-ca/operator_controller_trusted_ca_configmap.yaml
  openshift/manifests/18-configmap-openshift-operator-controller-operator-controller-trusted-ca-bundle.yml
  openshift/manifests/19-service-openshift-operator-controller-operator-controller-controller-manager-metrics-service.yml
  openshift/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
Labels: lgtm, qe-approved, jira/valid-reference, cherry-pick-approved, approved, jira/valid-bug, backport-risk-assessed

#225 OCPBUGS-48500: Upgrade golang.org/x/net (#1552)
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: lgtm, qe-approved, jira/valid-reference, cherry-pick-approved, approved, jira/valid-bug, backport-risk-assessed, jira/severity-important

#232 NO-ISSUE: Fix make verify and move operator-controller files
  openshift/Makefile
  openshift/operator-controller.Dockerfile
  openshift/operator-controller/.gitignore
  openshift/operator-controller/build-test-registry.sh
  openshift/operator-controller/dependencies.go
  openshift/operator-controller/generate-manifests.sh
  openshift/operator-controller/kustomize/overlays/openshift/kustomization.yaml
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/kustomization.yaml
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_log_verbosity.yaml
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_mount_etc_containers.yaml
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_node_selection.yaml
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_namespace_privileged.yaml
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_role.yaml
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_service.yaml
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/trusted-ca/operator_controller_trusted_ca_configmap.yaml
  openshift/operator-controller/kustomize/overlays/openshift/openshift-config/kustomization.yaml
  openshift/operator-controller/kustomize/overlays/openshift/openshift-config/rbac/operator-controller_manager_role.yaml
  openshift/operator-controller/kustomize/overlays/openshift/openshift-config/rbac/operator-controller_manager_role_binding.yaml
  openshift/operator-controller/manifests/00-namespace-openshift-operator-controller.yml
  openshift/operator-controller/manifests/01-customresourcedefinition-clusterextensions.olm.operatorframework.io.yml
  openshift/operator-controller/manifests/02-serviceaccount-openshift-operator-controller-operator-controller-controller-manager.yml
  openshift/operator-controller/manifests/03-role-openshift-config-operator-controller-manager-role.yml
  openshift/operator-controller/manifests/04-role-openshift-operator-controller-operator-controller-leader-election-role.yml
  openshift/operator-controller/manifests/05-role-openshift-operator-controller-operator-controller-manager-role.yml
  openshift/operator-controller/manifests/06-clusterrole-operator-controller-clusterextension-editor-role.yml
  openshift/operator-controller/manifests/07-clusterrole-operator-controller-clusterextension-viewer-role.yml
  openshift/operator-controller/manifests/08-clusterrole-operator-controller-extension-editor-role.yml
  openshift/operator-controller/manifests/09-clusterrole-operator-controller-extension-viewer-role.yml
  openshift/operator-controller/manifests/10-clusterrole-operator-controller-manager-role.yml
  openshift/operator-controller/manifests/11-clusterrole-operator-controller-metrics-reader.yml
  openshift/operator-controller/manifests/12-clusterrole-operator-controller-proxy-role.yml
  openshift/operator-controller/manifests/13-rolebinding-openshift-config-operator-controller-manager-rolebinding.yml
  openshift/operator-controller/manifests/14-rolebinding-openshift-operator-controller-operator-controller-leader-election-rolebinding.yml
  openshift/operator-controller/manifests/15-rolebinding-openshift-operator-controller-operator-controller-manager-rolebinding.yml
  openshift/operator-controller/manifests/16-clusterrolebinding-operator-controller-manager-rolebinding.yml
  openshift/operator-controller/manifests/17-clusterrolebinding-operator-controller-proxy-rolebinding.yml
  openshift/operator-controller/manifests/18-configmap-openshift-operator-controller-operator-controller-trusted-ca-bundle.yml
  openshift/operator-controller/manifests/19-service-openshift-operator-controller-operator-controller-service.yml
  openshift/operator-controller/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
  openshift/registry.Dockerfile
Labels: lgtm, jira/valid-reference, approved, acknowledge-critical-fixes-only

#234 OCPBUGS-46516: improve logging: catalog http server, op-con resolver
  catalogd/internal/serverutil/serverutil.go
  go.mod
  internal/resolve/catalog.go
  vendor/github.com/gorilla/handlers/.editorconfig
  vendor/github.com/gorilla/handlers/.gitignore
  vendor/github.com/gorilla/handlers/LICENSE
  vendor/github.com/gorilla/handlers/Makefile
  vendor/github.com/gorilla/handlers/README.md
  vendor/github.com/gorilla/handlers/canonical.go
  vendor/github.com/gorilla/handlers/compress.go
  vendor/github.com/gorilla/handlers/cors.go
  vendor/github.com/gorilla/handlers/doc.go
  vendor/github.com/gorilla/handlers/handlers.go
  vendor/github.com/gorilla/handlers/logging.go
  vendor/github.com/gorilla/handlers/proxy_headers.go
  vendor/github.com/gorilla/handlers/recovery.go
  vendor/modules.txt
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug, acknowledge-critical-fixes-only

#235 NO-ISSUE: Upgrade OCP images from 4.18 to 4.19
  openshift/registry.Dockerfile
Labels: lgtm, jira/valid-reference, approved, acknowledge-critical-fixes-only

#233 NO-ISSUE: Add catalogd manifests to start to run those tests
  openshift/Makefile
  openshift/catalogd.Dockerfile
  openshift/catalogd/dependencies.go
  openshift/catalogd/generate-manifests.sh
  openshift/catalogd/kustomize/overlays/openshift/catalogs/kustomization.yaml
  openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-certified-operators.yaml
  openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-community-operators.yaml
  openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-redhat-marketplace.yaml
  openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-redhat-operators.yaml
  openshift/catalogd/kustomize/overlays/openshift/kustomization.yaml
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/kustomization.yaml
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_log_verbosity.yaml
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_mount_etc_containers.yaml
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_node_selection.yaml
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/patches/manager_namespace_privileged.yaml
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/patches/manager_role.yaml
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/patches/manager_service.yaml
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/patches/mutating_webhook_config.yaml
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/trusted-ca/catalogd_trusted_ca_configmap.yaml
  openshift/catalogd/kustomize/overlays/openshift/openshift-config/kustomization.yaml
  openshift/catalogd/kustomize/overlays/openshift/openshift-config/rbac/catalogd_manager_role.yaml
  openshift/catalogd/kustomize/overlays/openshift/openshift-config/rbac/catalogd_manager_role_binding.yaml
  openshift/catalogd/manifests/00-namespace-openshift-catalogd.yml
  openshift/catalogd/manifests/01-customresourcedefinition-clustercatalogs.olm.operatorframework.io.yml
  openshift/catalogd/manifests/02-serviceaccount-openshift-catalogd-catalogd-controller-manager.yml
  openshift/catalogd/manifests/03-role-openshift-catalogd-catalogd-leader-election-role.yml
  openshift/catalogd/manifests/04-role-openshift-config-catalogd-manager-role.yml
  openshift/catalogd/manifests/05-clusterrole-catalogd-manager-role.yml
  openshift/catalogd/manifests/06-clusterrole-catalogd-metrics-reader.yml
  openshift/catalogd/manifests/07-clusterrole-catalogd-proxy-role.yml
  openshift/catalogd/manifests/08-rolebinding-openshift-catalogd-catalogd-leader-election-rolebinding.yml
  openshift/catalogd/manifests/09-rolebinding-openshift-config-catalogd-manager-rolebinding.yml
  openshift/catalogd/manifests/10-clusterrolebinding-catalogd-manager-rolebinding.yml
  openshift/catalogd/manifests/11-clusterrolebinding-catalogd-proxy-rolebinding.yml
  openshift/catalogd/manifests/12-configmap-openshift-catalogd-catalogd-trusted-ca-bundle.yml
  openshift/catalogd/manifests/13-service-openshift-catalogd-catalogd-service.yml
  openshift/catalogd/manifests/14-deployment-openshift-catalogd-catalogd-controller-manager.yml
  openshift/catalogd/manifests/15-clustercatalog-openshift-certified-operators.yml
  openshift/catalogd/manifests/16-clustercatalog-openshift-community-operators.yml
  openshift/catalogd/manifests/17-clustercatalog-openshift-redhat-marketplace.yml
  openshift/catalogd/manifests/18-clustercatalog-openshift-redhat-operators.yml
  openshift/catalogd/manifests/19-mutatingwebhookconfiguration-catalogd-mutating-webhook-configuration.yml
Labels: lgtm, jira/valid-reference, approved, acknowledge-critical-fixes-only

#236 OCPBUGS-48813: improve logging: catalog http server, op-con resolver [release-4.18]
  internal/resolve/catalog.go
Labels: lgtm, jira/valid-reference, cherry-pick-approved, approved, jira/valid-bug, backport-risk-assessed

#237 OCPBUGS-48830: resolve issue with pre-mature mounting of trusted CA configmap
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
  openshift/catalogd/manifests/14-deployment-openshift-catalogd-catalogd-controller-manager.yml
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
  openshift/operator-controller/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug, jira/severity-important, acknowledge-critical-fixes-only

#238 OCPBUGS-48795: Add /etc/docker to the operator-controller and catalogd deployments
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_mount_etc_containers.yaml
  openshift/catalogd/manifests/14-deployment-openshift-catalogd-catalogd-controller-manager.yml
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_mount_etc_containers.yaml
  openshift/operator-controller/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug, jira/severity-important, acknowledge-critical-fixes-only

#241 NO-ISSUE: UPSTREAM: <carry>: fixup catalogd.Dockerfile paths
  openshift/catalogd.Dockerfile
Labels: lgtm, jira/valid-reference, approved, acknowledge-critical-fixes-only

#239 OCPBUGS-49299: [release-4.18] UPSTREAM: <carry>: resolve issue with pre-mature mounting of trusted CA configmap
  openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
  openshift/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
Labels: lgtm, qe-approved, jira/valid-reference, cherry-pick-approved, approved, jira/valid-bug, backport-risk-assessed, jira/severity-important, acknowledge-critical-fixes-only

#245 OCPBUGS-49418: Resolve issue with pre-mature mounting of service CA configmap
  openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
  openshift/catalogd/manifests/14-deployment-openshift-catalogd-catalogd-controller-manager.yml
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
  openshift/operator-controller/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug, jira/severity-important, acknowledge-critical-fixes-only

#247 OCPBUGS-49439: Resolve issue with pre-mature mounting of service CA configmap
  openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
  openshift/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
Labels: lgtm, jira/valid-reference, cherry-pick-approved, approved, jira/valid-bug, backport-risk-assessed, jira/severity-important, acknowledge-critical-fixes-only

#249 OCPBUGS-48765: leaderelection settings
  catalogd/cmd/catalogd/main.go
  cmd/operator-controller/main.go
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug, acknowledge-critical-fixes-only

#251 OCPBUGS-49622: Fix leaderelection settings
  cmd/manager/main.go
Labels: lgtm, jira/valid-reference, cherry-pick-approved, approved, jira/valid-bug, backport-risk-assessed
