Repository openshift/operator-framework-operator-controller, pull requests merged in 2025-04, with the labels that each got.

#304 OCPBUGS-52618: Bump jinja2 from 3.1.5 to 3.1.6
  requirements.txt
Labels: lgtm, jira/valid-reference, cherry-pick-approved, approved, jira/valid-bug, backport-risk-assessed, jira/severity-important

#314 OCPBUGS-54877: UPSTREAM: <drop>: Fix log initialization (#1917)
  cmd/catalogd/main.go
  cmd/operator-controller/main.go
  go.mod
  vendor/k8s.io/klog/v2/internal/verbosity/verbosity.go
  vendor/k8s.io/klog/v2/textlogger/options.go
  vendor/k8s.io/klog/v2/textlogger/textlogger.go
  vendor/k8s.io/klog/v2/textlogger/textlogger_slog.go
  vendor/modules.txt
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug

#317 NO-ISSUE: Update certpoolwatcher log levels
  internal/shared/util/http/certlog.go
  internal/shared/util/http/certutil.go
Labels: lgtm, jira/valid-reference, approved

#316 OCPBUGS-54877: Add catalogd-cas-dir option to op-con
  openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
  openshift/operator-controller/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
Labels: lgtm, qe-approved, jira/valid-reference, approved, jira/valid-bug

#318 OCPBUGS-51241,OCPBUGS-51243: Bump github.com/go-jose/go-jose/v4 from 4.0.4 to 4.0.5
  go.mod
  go.sum
  vendor/github.com/go-jose/go-jose/v4/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/v4/README.md
  vendor/github.com/go-jose/go-jose/v4/crypter.go
  vendor/github.com/go-jose/go-jose/v4/jwe.go
  vendor/github.com/go-jose/go-jose/v4/jwk.go
  vendor/github.com/go-jose/go-jose/v4/jws.go
  vendor/github.com/go-jose/go-jose/v4/opaque.go
  vendor/github.com/go-jose/go-jose/v4/signing.go
  vendor/modules.txt
Labels: lgtm, jira/valid-reference, cherry-pick-approved, approved, jira/valid-bug, backport-risk-assessed, jira/severity-moderate

#323 OCPBUGS-55172: Add catalogd-cas-dir option to op-con [release-4.18]
  openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
  openshift/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
Labels: lgtm, qe-approved, jira/valid-reference, cherry-pick-approved, approved, jira/valid-bug, backport-risk-assessed

#319 OCPBUGS-52617: Bump jinja2 from 3.1.5 to 3.1.6 [release-4.17]
  requirements.txt
Labels: lgtm, jira/valid-reference, cherry-pick-approved, approved, jira/valid-bug, backport-risk-assessed, jira/severity-important

#324 OCPBUGS-48478: [release-4.18] - Add openshift node selector annotation (operator-controller ONLY)
  openshift/generate-manifests.sh
  openshift/kustomize/overlays/openshift/olmv1-ns/kustomization.yaml
  openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_namespace_annotations.yaml
  openshift/manifests/00-namespace-openshift-operator-controller.yml
Labels: lgtm, qe-approved, jira/valid-reference, cherry-pick-approved, approved, jira/valid-bug, backport-risk-assessed, jira/severity-moderate
