Repository openshift/operator-framework-operator-controller, pull requests merged in 2025-03, with the labels that each got.

#281 [release-4.18] OCPBUGS-52173: unset PAXRecords and Xattrs in image layers when applying to disk
  internal/rukpak/source/containers_image.go
  internal/rukpak/source/containers_image_internal_test.go
Labels: lgtm, qe-approved, jira/valid-reference, cherry-pick-approved, approved, jira/valid-bug, backport-risk-assessed, jira/severity-important

#275 [release-4.18] OCPBUGS-52246: Enable Upstream E2E for 4.18
  openshift/Makefile
  openshift/build-test-registry.sh
  openshift/registry.Dockerfile
Labels: lgtm, jira/valid-reference, jira/severity-low, cherry-pick-approved, approved, jira/valid-bug, backport-risk-assessed

#287 NO-ISSUE: UPSTREAM: <carry>: Update DOWNSTREAM_OWNERS_ALIASES
  DOWNSTREAM_OWNERS_ALIASES
Labels: lgtm, jira/valid-reference, approved
