Repository openshift/operator-framework-operator-controller, pull requests merged in 2025-10, with the labels that each got.

#497 NO-ISSUE: Synchronize From Upstream Repositories
  cmd/operator-controller/main.go
  commitchecker.yaml
  go.mod
  go.sum
  internal/operator-controller/applier/boxcutter_test.go
  internal/operator-controller/applier/provider.go
  internal/operator-controller/applier/provider_test.go
  internal/operator-controller/rukpak/bundle/source/source.go
  internal/operator-controller/rukpak/bundle/source/source_test.go
  internal/operator-controller/rukpak/render/registryv1/generators/generators_test.go
  internal/operator-controller/rukpak/render/registryv1/registryv1_test.go
  internal/operator-controller/rukpak/render/registryv1/validators/validator_test.go
  internal/operator-controller/rukpak/render/render_test.go
  internal/operator-controller/rukpak/util/testing/bundlefs.go
  internal/operator-controller/rukpak/util/testing/bundlefs/bundlefs.go
  internal/operator-controller/rukpak/util/testing/bundlefs/bundlefs_test.go
  internal/operator-controller/rukpak/util/testing/clusterserviceversion/builder.go
  internal/operator-controller/rukpak/util/testing/clusterserviceversion/builder_test.go
  internal/operator-controller/rukpak/util/testing/testing.go
  internal/operator-controller/rukpak/util/testing/testing_test.go
  requirements.txt
  vendor/modules.txt
Labels: lgtm, qe-approved, jira/valid-reference, approved, tide/merge-method-merge, verified

#496 OCPBUGS-62722: (cherry-pick) Fix truncate large error messages and unhandle changes for crd upgrade safety in status conditions
  internal/operator-controller/controllers/clusterextension_controller.go
  internal/operator-controller/controllers/common_controller.go
  internal/operator-controller/controllers/common_controller_test.go
  internal/operator-controller/rukpak/preflights/crdupgradesafety/crdupgradesafety.go
  internal/operator-controller/rukpak/preflights/crdupgradesafety/crdupgradesafety_test.go
  internal/operator-controller/rukpak/preflights/crdupgradesafety/unhandled_message_test.go
  testdata/manifests/crd-unhandled-new.json
  testdata/manifests/crd-unhandled-old.json
Labels: lgtm, qe-approved, jira/valid-reference, approved, jira/valid-bug, backport-risk-assessed, jira/severity-important, verified

#503 OCPBUGS-62811: for incompatible test add func to wait builder and deployer SA creation by OCP controller
  openshift/tests-extension/pkg/helpers/cluster_extension.go
  openshift/tests-extension/test/olmv1-incompatible.go
Labels: lgtm, qe-approved, jira/valid-reference, approved, jira/valid-bug, backport-risk-assessed, verified
